name: Generate Snake Game

# Controls when the action will run.
on:
    schedule: # Runs at 12am UTC daily
      - cron: "0 0 * * *"
  
    # Allows manual workflow trigger
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: JustinCordova # Replace with your actual GitHub username
          github_token: ${{ secrets.GITHUB_TOKEN }} # Use the default token provided by GitHub

      - name: Upload Snake Game
        uses: actions/upload-artifact@v3
        with:
          name: snake-game
          path: dist/github-contribution-grid-snake.svg
