name: generate animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: '0 5 * * *'
  
  # Allows to manually run the job at any time
  workflow_dispatch:
  
  # Run on every push on the master branch
  push:
    branches:
      - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Generates a snake game from a GitHub user's contributions graph, outputting SVG animations
      - name: Generate GitHub Contribution Grid Snake Animation
        uses: Platane/snk/svg-only@v3  # Ensure this action is updated and compatible with Node.js 20
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Push the content of <build_dir> to a branch
      # The content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>, or as a GitHub page
      - name: Push GitHub Contribution Grid Snake SVG to the Output Branch
        uses: crazy-max/ghaction-github-pages@v4  # Updated to version 4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
